name = "navarchos"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[[kv_namespaces]]
binding = "NAVAR_KV"
id = "03eb57f4efb645aca7212cce467ff068"
preview_id = "6cabd6a9ab87416fb5846e125b35858b"

[[r2_buckets]]
binding = "NAVAR_BUCKET"
bucket_name = "navarchos"
preview_bucket_name = "navarchos-preview"